name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build
        working-directory: ./docs
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "spacebudz-lucid"
          import-map: "./docs/import_map.json"
          entrypoint: "./docs/serve.ts"
