name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build, lint, and test on Deno and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Deno
        uses: denoland/setup-deno@v2

      - name: build
        run: deno task build

      - name: Lint
        run: deno lint

      - name: Test
        run: deno task test
